import 'fhir_isar.dart';

IsarResource mapToIsarResource(Map<String, dynamic> map) {
  switch (map['resourceType']!) {
    case 'Account':
      return IsarAccount.fromMap(map);
    case 'ActivityDefinition':
      return IsarActivityDefinition.fromMap(map);
    case 'AdministrableProductDefinition':
      return IsarAdministrableProductDefinition.fromMap(map);
    case 'AdverseEvent':
      return IsarAdverseEvent.fromMap(map);
    case 'AllergyIntolerance':
      return IsarAllergyIntolerance.fromMap(map);
    case 'Appointment':
      return IsarAppointment.fromMap(map);
    case 'AppointmentResponse':
      return IsarAppointmentResponse.fromMap(map);
    case 'AuditEvent':
      return IsarAuditEvent.fromMap(map);
    case 'Basic':
      return IsarBasic.fromMap(map);
    case 'Binary':
      return IsarBinary.fromMap(map);
    case 'BiologicallyDerivedProduct':
      return IsarBiologicallyDerivedProduct.fromMap(map);
    case 'BodyStructure':
      return IsarBodyStructure.fromMap(map);
    case 'Bundle':
      return IsarBundle.fromMap(map);
    case 'CapabilityStatement':
      return IsarCapabilityStatement.fromMap(map);
    case 'CarePlan':
      return IsarCarePlan.fromMap(map);
    case 'CareTeam':
      return IsarCareTeam.fromMap(map);
    case 'CatalogEntry':
      return IsarCatalogEntry.fromMap(map);
    case 'ChargeItem':
      return IsarChargeItem.fromMap(map);
    case 'ChargeItemDefinition':
      return IsarChargeItemDefinition.fromMap(map);
    case 'Citation':
      return IsarCitation.fromMap(map);
    case 'Claim':
      return IsarClaim.fromMap(map);
    case 'ClaimResponse':
      return IsarClaimResponse.fromMap(map);
    case 'ClinicalImpression':
      return IsarClinicalImpression.fromMap(map);
    case 'ClinicalUseDefinition':
      return IsarClinicalUseDefinition.fromMap(map);
    case 'CodeSystem':
      return IsarCodeSystem.fromMap(map);
    case 'Communication':
      return IsarCommunication.fromMap(map);
    case 'CommunicationRequest':
      return IsarCommunicationRequest.fromMap(map);
    case 'CompartmentDefinition':
      return IsarCompartmentDefinition.fromMap(map);
    case 'Composition':
      return IsarComposition.fromMap(map);
    case 'ConceptMap':
      return IsarConceptMap.fromMap(map);
    case 'Condition':
      return IsarCondition.fromMap(map);
    case 'Consent':
      return IsarConsent.fromMap(map);
    case 'Contract':
      return IsarContract.fromMap(map);
    case 'Coverage':
      return IsarCoverage.fromMap(map);
    case 'CoverageEligibilityRequest':
      return IsarCoverageEligibilityRequest.fromMap(map);
    case 'CoverageEligibilityResponse':
      return IsarCoverageEligibilityResponse.fromMap(map);
    case 'DetectedIssue':
      return IsarDetectedIssue.fromMap(map);
    case 'Device':
      return IsarDevice.fromMap(map);
    case 'DeviceDefinition':
      return IsarDeviceDefinition.fromMap(map);
    case 'DeviceMetric':
      return IsarDeviceMetric.fromMap(map);
    case 'DeviceRequest':
      return IsarDeviceRequest.fromMap(map);
    case 'DeviceUseStatement':
      return IsarDeviceUseStatement.fromMap(map);
    case 'DiagnosticReport':
      return IsarDiagnosticReport.fromMap(map);
    case 'DocumentManifest':
      return IsarDocumentManifest.fromMap(map);
    case 'DocumentReference':
      return IsarDocumentReference.fromMap(map);
    case 'Encounter':
      return IsarEncounter.fromMap(map);
    case 'Endpoint':
      return IsarEndpoint.fromMap(map);
    case 'EnrollmentRequest':
      return IsarEnrollmentRequest.fromMap(map);
    case 'EnrollmentResponse':
      return IsarEnrollmentResponse.fromMap(map);
    case 'EpisodeOfCare':
      return IsarEpisodeOfCare.fromMap(map);
    case 'EventDefinition':
      return IsarEventDefinition.fromMap(map);
    case 'Evidence':
      return IsarEvidence.fromMap(map);
    case 'EvidenceReport':
      return IsarEvidenceReport.fromMap(map);
    case 'EvidenceVariable':
      return IsarEvidenceVariable.fromMap(map);
    case 'ExampleScenario':
      return IsarExampleScenario.fromMap(map);
    case 'ExplanationOfBenefit':
      return IsarExplanationOfBenefit.fromMap(map);
    case 'FamilyMemberHistory':
      return IsarFamilyMemberHistory.fromMap(map);
    case 'Flag':
      return IsarFlag.fromMap(map);
    case 'Goal':
      return IsarGoal.fromMap(map);
    case 'GraphDefinition':
      return IsarGraphDefinition.fromMap(map);
    case 'Group':
      return IsarGroup.fromMap(map);
    case 'GuidanceResponse':
      return IsarGuidanceResponse.fromMap(map);
    case 'HealthcareService':
      return IsarHealthcareService.fromMap(map);
    case 'ImagingStudy':
      return IsarImagingStudy.fromMap(map);
    case 'Immunization':
      return IsarImmunization.fromMap(map);
    case 'ImmunizationEvaluation':
      return IsarImmunizationEvaluation.fromMap(map);
    case 'ImmunizationRecommendation':
      return IsarImmunizationRecommendation.fromMap(map);
    case 'ImplementationGuide':
      return IsarImplementationGuide.fromMap(map);
    case 'Ingredient':
      return IsarIngredient.fromMap(map);
    case 'InsurancePlan':
      return IsarInsurancePlan.fromMap(map);
    case 'Invoice':
      return IsarInvoice.fromMap(map);
    case 'Library':
      return IsarLibrary.fromMap(map);
    case 'Linkage':
      return IsarLinkage.fromMap(map);
    case 'List':
      return IsarList.fromMap(map);
    case 'Location':
      return IsarLocation.fromMap(map);
    case 'ManufacturedItemDefinition':
      return IsarManufacturedItemDefinition.fromMap(map);
    case 'Measure':
      return IsarMeasure.fromMap(map);
    case 'MeasureReport':
      return IsarMeasureReport.fromMap(map);
    case 'Media':
      return IsarMedia.fromMap(map);
    case 'Medication':
      return IsarMedication.fromMap(map);
    case 'MedicationAdministration':
      return IsarMedicationAdministration.fromMap(map);
    case 'MedicationDispense':
      return IsarMedicationDispense.fromMap(map);
    case 'MedicationKnowledge':
      return IsarMedicationKnowledge.fromMap(map);
    case 'MedicationRequest':
      return IsarMedicationRequest.fromMap(map);
    case 'MedicationStatement':
      return IsarMedicationStatement.fromMap(map);
    case 'MedicinalProductDefinition':
      return IsarMedicinalProductDefinition.fromMap(map);
    case 'MessageDefinition':
      return IsarMessageDefinition.fromMap(map);
    case 'MessageHeader':
      return IsarMessageHeader.fromMap(map);
    case 'MolecularSequence':
      return IsarMolecularSequence.fromMap(map);
    case 'NamingSystem':
      return IsarNamingSystem.fromMap(map);
    case 'NutritionOrder':
      return IsarNutritionOrder.fromMap(map);
    case 'NutritionProduct':
      return IsarNutritionProduct.fromMap(map);
    case 'Observation':
      return IsarObservation.fromMap(map);
    case 'ObservationDefinition':
      return IsarObservationDefinition.fromMap(map);
    case 'OperationDefinition':
      return IsarOperationDefinition.fromMap(map);
    case 'OperationOutcome':
      return IsarOperationOutcome.fromMap(map);
    case 'Organization':
      return IsarOrganization.fromMap(map);
    case 'OrganizationAffiliation':
      return IsarOrganizationAffiliation.fromMap(map);
    case 'PackagedProductDefinition':
      return IsarPackagedProductDefinition.fromMap(map);
    case 'Parameters':
      return IsarParameters.fromMap(map);
    case 'Patient':
      return IsarPatient.fromMap(map);
    case 'PaymentNotice':
      return IsarPaymentNotice.fromMap(map);
    case 'PaymentReconciliation':
      return IsarPaymentReconciliation.fromMap(map);
    case 'Person':
      return IsarPerson.fromMap(map);
    case 'PlanDefinition':
      return IsarPlanDefinition.fromMap(map);
    case 'Practitioner':
      return IsarPractitioner.fromMap(map);
    case 'PractitionerRole':
      return IsarPractitionerRole.fromMap(map);
    case 'Procedure':
      return IsarProcedure.fromMap(map);
    case 'Provenance':
      return IsarProvenance.fromMap(map);
    case 'Questionnaire':
      return IsarQuestionnaire.fromMap(map);
    case 'QuestionnaireResponse':
      return IsarQuestionnaireResponse.fromMap(map);
    case 'RegulatedAuthorization':
      return IsarRegulatedAuthorization.fromMap(map);
    case 'RelatedPerson':
      return IsarRelatedPerson.fromMap(map);
    case 'RequestGroup':
      return IsarRequestGroup.fromMap(map);
    case 'ResearchDefinition':
      return IsarResearchDefinition.fromMap(map);
    case 'ResearchElementDefinition':
      return IsarResearchElementDefinition.fromMap(map);
    case 'ResearchStudy':
      return IsarResearchStudy.fromMap(map);
    case 'ResearchSubject':
      return IsarResearchSubject.fromMap(map);
    case 'RiskAssessment':
      return IsarRiskAssessment.fromMap(map);
    case 'Schedule':
      return IsarSchedule.fromMap(map);
    case 'SearchParameter':
      return IsarSearchParameter.fromMap(map);
    case 'ServiceRequest':
      return IsarServiceRequest.fromMap(map);
    case 'Slot':
      return IsarSlot.fromMap(map);
    case 'Specimen':
      return IsarSpecimen.fromMap(map);
    case 'SpecimenDefinition':
      return IsarSpecimenDefinition.fromMap(map);
    case 'StructureDefinition':
      return IsarStructureDefinition.fromMap(map);
    case 'StructureMap':
      return IsarStructureMap.fromMap(map);
    case 'Subscription':
      return IsarSubscription.fromMap(map);
    case 'SubscriptionStatus':
      return IsarSubscriptionStatus.fromMap(map);
    case 'SubscriptionTopic':
      return IsarSubscriptionTopic.fromMap(map);
    case 'Substance':
      return IsarSubstance.fromMap(map);
    case 'SubstanceDefinition':
      return IsarSubstanceDefinition.fromMap(map);
    case 'SupplyDelivery':
      return IsarSupplyDelivery.fromMap(map);
    case 'SupplyRequest':
      return IsarSupplyRequest.fromMap(map);
    case 'Task':
      return IsarTask.fromMap(map);
    case 'TerminologyCapabilities':
      return IsarTerminologyCapabilities.fromMap(map);
    case 'TestReport':
      return IsarTestReport.fromMap(map);
    case 'TestScript':
      return IsarTestScript.fromMap(map);
    case 'ValueSet':
      return IsarValueSet.fromMap(map);
    case 'VerificationResult':
      return IsarVerificationResult.fromMap(map);
    case 'VisionPrescription':
      return IsarVisionPrescription.fromMap(map);
  }
  return IsarResource.fromMap(map);
}
